### ISSUE TITLE
DCA into multiple currencies

### ISSUE THREAD

**Issue by Dimo99** [raphaellueckl/kraken-dca#4]
Maybe it could be implemented that also other currencies are supported.
I want to DCA into ETH and BTC 50/50. 
So my current plan for the easiest way to do that.
 - Add modifications to the script so it works for ETH also. 
 - Run the two scripts for BTC and ETH in parallel. 
  -  divide the available fiat amount in half so that the script can DCA equal amounts into ETH and BTC.
    ??? I am still wondering what will be the best and easiest way to do that. Because if I just divide the current `fiatAmount` in half I think more BTC will be accumulated because the minimum order size for BTC is smaller and it will be bought more often.

**Comment by raphaellueckl** [comment]
Hi Dimo99

Sorry, just now saw, that people wrote issues.
I want to keep it bitcoin only, as all other coins than bitcoin are shitcoins in my view.

But since this is open source, the project can be forked and adapted into your own project, if you want to add that. I don't want more complexity in my script for something that I see no actual value in.

I hope this answer finds you well. You can maybe just switch "BTC" for "ETH" in the lines of code and then adapt the minimum order size. Might be that it is a bit more complex than that.

Cheers
Raphael
